const icpmsSteps = [
  {
    id: "sample",
    gl: { title: "1. Introdución da mostra", text: "A disolución líquida transfórmase nun aerosol fino mediante un sistema de nebulización." },
    en: { title: "1. Sample introduction", text: "The liquid solution is transformed into a fine aerosol using a nebulization system." }
  },
  {
    id: "plasma",
    gl: { title: "2. Plasma de argon", text: "O aerosol transpórtase cara ao plasma (Ar), xerado por un campo electromagnético que alcanza os 6.000-10.000 K, onde se produce a atomización e ionización dos elementos." },
    en: { title: "2. Argon plasma", text: "The aerosol is carried into the plasma (Ar), generated by an electromagnetic field reaching 6,000-10,000 K, where atomization and ionization of the elements occurs." }
  },
  {
    id: "interface",
    gl: { title: "3. Interface (conos)", text: "Os ións atravesan dous conos metálicos (sampler e skimmer) que permiten a súa transferencia desde o plasma, a presión atmosférica, cara ao alto baleiro do espectrómetro." },
    en: { title: "3. Interface (cones)", text: "The ions pass through two metal cones (sampler and skimmer), allowing their transfer from the plasma, at atmospheric pressure, into the mass spectrometer's high vacuum." }
  },
  {
    id: "lenses",
    gl: { title: "4. Lentes iónicas", text: "Focalizan e guían o feixe de ións cara ao analizador de masas, minimizando perdas de sinal." },
    en: { title: "4. Ion lenses", text: "Focus and guide the ion beam towards the mass analyzer, minimizing signal loss." }
  },
  {
    id: "analyzer",
    gl: { title: "5. Analizador (TOF)", text: "Separa os ións segundo a súa relación masa/carga (m/z). No ICP-MS-TOF, isto permite medir decenas de isótopos de forma cuasi-simultánea." },
    en: { title: "5. Analyzer (TOF)", text: "Separates ions according to their mass-to-charge ratio (m/z). In ICP-MS-TOF, this allows dozens of isotopes to be measured quasi-simultaneously." }
  },
  {
    id: "detector",
    gl: { title: "6. Detector de ións", text: "Transforma os ións nunha sinal eléctrica proporcional á súa abundancia, permitindo a cuantificación de cada elemento." },
    en: { title: "6. Ion detector", text: "Converts the ions into an electrical signal proportional to their abundance, allowing quantification of each element." }
  }
];

function renderIcpmsDiagram() {
  const container = document.getElementById("icpms-diagram");
  if (!container) return;

  const lang = currentLang === "gl" ? "gl" : "en";

  const svg = `
    <svg viewBox="0 0 800 220" xmlns="http://www.w3.org/2000/svg" class="icpms-svg">
      <line x1="60" y1="110" x2="740" y2="110" stroke="#d8d5cf" stroke-width="2" stroke-dasharray="4 4"/>
      ${icpmsSteps.map((step, i) => {
        const x = 60 + i * 136;
        return `
          <g class="icpms-node" data-step="${step.id}" tabindex="0">
            <circle cx="${x}" cy="110" r="34" />
            <text x="${x}" y="116" text-anchor="middle" class="icpms-num">${i + 1}</text>
          </g>
        `;
      }).join("")}
    </svg>
  `;

  const labels = icpmsSteps.map((step, i) => {
    const x = 60 + i * 136;
    return `<div class="icpms-label" style="left:${(x / 800) * 100}%">${step[lang].title.split(". ")[1] || step[lang].title}</div>`;
  }).join("");

  container.innerHTML = `
    <div class="icpms-svg-wrapper">${svg}</div>
    <div class="icpms-labels-row">${labels}</div>
    <div class="icpms-detail" id="icpms-detail">
      <p class="corr-detail-empty">${lang === "gl" ? "Fai clic nun paso do diagrama para ver o detalle." : "Click a step in the diagram to see details."}</p>
    </div>
  `;

  container.querySelectorAll(".icpms-node").forEach(node => {
    node.addEventListener("click", () => showIcpmsDetail(node.dataset.step));
    node.addEventListener("keypress", (e) => { if (e.key === "Enter") showIcpmsDetail(node.dataset.step); });
  });
}

function showIcpmsDetail(stepId) {
  const step = icpmsSteps.find(s => s.id === stepId);
  const lang = currentLang === "gl" ? "gl" : "en";
  document.getElementById("icpms-detail").innerHTML = `
    <h3>${step[lang].title}</h3>
    <p>${step[lang].text}</p>
  `;
}

renderIcpmsDiagram();